# Generated by Django 3.1.5 on 2021-01-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
