# Generated by Django 3.1.5 on 2021-01-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrito', '0002_auto_20210116_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='grupo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Deseja entrar em nosso grupo?'),
        ),
    ]
