# Generated by Django 3.1.5 on 2021-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
