# Generated by Django 3.1.5 on 2021-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210116_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, upload_to='core/categorias', verbose_name='Icone da categoria'),
        ),
    ]
