# Generated by Django 3.1.5 on 2021-01-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='descricao',
            field=models.TextField(default='teste', max_length=100, verbose_name='Segunda frase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='pergunta',
            field=models.CharField(default='teste', max_length=100, verbose_name='Segundo título'),
            preserve_default=False,
        ),
    ]
