# Generated by Django 3.1.5 on 2021-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210116_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(default='teste', max_length=100, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
    ]
