# Generated by Django 3.1.5 on 2021-01-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_banner_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='subtitulo',
        ),
    ]
