# Generated by Django 3.1.5 on 2021-01-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_banner_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.TextField(max_length=100, verbose_name='Subtítulo')),
                ('texto', models.TextField(max_length=300, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Quem somos',
                'verbose_name_plural': 'Quem somos',
            },
        ),
    ]
