# Generated by Django 3.1.5 on 2021-01-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quemsomos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemsomos',
            name='subtitulo',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
    ]
