# Generated by Django 3.1.5 on 2021-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210116_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quemsomos',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Texto'),
        ),
    ]
