# Generated by Django 3.1.5 on 2021-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='benificios',
            field=models.TextField(blank=True, max_length=500, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inscrições até'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='vagas',
            field=models.TextField(blank=True, max_length=500, verbose_name='Vagas'),
        ),
    ]
