# Generated by Django 3.1.5 on 2021-01-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210117_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidade',
            old_name='benificios',
            new_name='beneficios',
        ),
    ]
