# Generated by Django 3.1.5 on 2021-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210117_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link_doacao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='link_instagram',
            field=models.TextField(blank=True, max_length=500, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Inscrições até'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='link_inscricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Benefícios'),
        ),
    ]
