# Generated by Django 3.1.5 on 2021-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210117_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.FileField(blank=True, storage='core/categorias', upload_to='', verbose_name='Icone da categoria'),
        ),
    ]
