# Generated by Django 3.1.5 on 2021-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210117_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, upload_to='core/categorias', verbose_name='Icone da categoria'),
        ),
    ]
