# Generated by Django 3.1.5 on 2021-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210117_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='area_de_atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área de atuação'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='link_inscricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='link de inscrição'),
        ),
    ]
