# Generated by Django 3.1.5 on 2021-01-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210117_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='link_doacao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Link para doações'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='link_instagram',
            field=models.TextField(blank=True, max_length=500, verbose_name='Link para o instagram'),
        ),
    ]
